version: '3'
services:
  backend:
    image: ahm1376/backend:latest
    ports:
      - "5200:5200"
    restart: always
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - app-network

  frontend:
    image: ahm1376/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge